# Generated by Django 4.1.5 on 2023-02-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutoBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="AutoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autoseller.autobrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mpg", models.FloatField(null=True)),
                ("cyl", models.SmallIntegerField(null=True)),
                ("disp", models.FloatField(null=True)),
                ("hp", models.FloatField(null=True)),
                ("drat", models.FloatField(null=True)),
                ("wt", models.FloatField(null=True)),
                ("qsec", models.FloatField(null=True)),
                ("vs", models.SmallIntegerField(null=True)),
                ("am", models.SmallIntegerField(null=True)),
                ("gear", models.SmallIntegerField(null=True)),
                ("carb", models.SmallIntegerField(null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="autoseller.automodel",
                    ),
                ),
            ],
        ),
    ]
