# Generated by Django 4.1.5 on 2023-02-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoseller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autobrand",
            name="name",
            field=models.CharField(default="", max_length=128, unique=True),
        ),
    ]
