# Generated by Django 4.1.5 on 2023-02-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autoseller", "0002_alter_autobrand_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="automodel",
            unique_together={("name", "brand")},
        ),
    ]
